

import "./globals.css";
import Providers from "./Providers";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full"
    >
      <body className="min-h-full flex flex-col">

        <Providers>
          {children}
          <Toaster position="top-right" />
        </Providers>

        </body>
    </html>
  );
}
